@ECHO OFF

Rem Create Directories

mkdir "New Website"
cd "New Website"
mkdir resources
mkdir playground
cd resources
mkdir js
mkdir css
mkdir lib
mkdir doc
mkdir img
cd css
mkdir fonts
cd ..
cd ..

Rem Generate Index file with imports

(
echo <!DOCTYPE html>
echo 
echo <!--
echo     *Generated by WSG Tool*
echo     *By: Ahmed Amgad :: http://a2mproductions.com :: http://gitgub.com/Website-Structure-Generator
echo -->
echo 
echo <html lang ="en">
echo    <head>
echo      <meta charset="UTF-8">
echo      <title>New Website</title>
echo      <link rel="icon" href="resources/img/icon.ico">
echo      <meta http-equiv="X-UA-Compatible" content="IE=edge">
echo      <meta name="viewport" content="width=device-width, initial-scale=1.0">
echo 
echo      <script src="resources/js/jquery.js"></script>
echo      <script src="resources/js/bootstrap.min.js"></script>
echo      <script src="resources/js/npm.js"></script>
echo      <link rel="stylesheet" type="text/css" href="resources/css/bootstrap.min.css">
echo      <link rel="stylesheet" type="text/css" href="resources/css/style.css">
echo    </head>
echo 
echo    <body>
echo 	<h1>Generation Sucessful</h1>
echo 	<h3>Generated by WSG Tool</h3>
echo    </body>
echo    
echo  </html>
) > index.html